### ISSUE TITLE
Display in SBFspot Widget no as expected

### ISSUE THREAD

**Issue by Tottback** [rg-engineering/ioBroker.sbfspot#11]
SBFspot widget showing not the expected result with sqlite3 database
With "today" no values appears. The others are working but no x-axes appear.
Some values in years/12 months also appear strange.

![sbfspot_setting](https://user-images.githubusercontent.com/39876346/51837992-56d32e80-2305-11e9-9f9c-3e748ae1f8dc.PNG)
![sbfspot_30d](https://user-images.githubusercontent.com/39876346/51837932-2c817100-2305-11e9-9f62-4a87542597c6.PNG)
![sbfspot_12m](https://user-images.githubusercontent.com/39876346/51837959-402cd780-2305-11e9-85f1-ab229bfe27b9.PNG)
![sbfspot_years](https://user-images.githubusercontent.com/39876346/51837935-2e4b3480-2305-11e9-8fa7-8fdd1eaafc3a.PNG)
![sbfspot_objects](https://user-images.githubusercontent.com/39876346/51837953-3c995080-2305-11e9-99b8-3de69239bb8f.PNG)

**Comment by Tottback** [comment]
X-axis now appear after changing the colour (!= 0xffffff). The todays view still show no values.

**Comment by rg-engineering** [comment]
solved with 2.4.3
