### ISSUE TITLE
Disable data pulling during the night

### ISSUE THREAD

**Issue by martinschm** [rg-engineering/ioBroker.sbfspot#19]
Hi,
the adapter always connects to the SMA device even though there won't be any updates during the night. Maybe it could make sense to pause it during the night or after sun set.

Would reduce load on the systems.

**Comment by rg-engineering** [comment]
sbfspot itself stops polling data during the night. I'll check to do the same from adpater side. But I set this feature request to a lower priority...

**Comment by martinschm** [comment]
Cool, thanks a lot.

**Comment by rg-engineering** [comment]
solved with V3.0.0
