### ISSUE TITLE
exception in DB_GetInverters (exception in DB_GetInverters [SqliteError: attempt to write a readonly database])

### ISSUE THREAD

**Issue by runrennerrun** [rg-engineering/ioBroker.sbfspot#276]
Hi, 

although I see data from my inverter coming in via mqtt (not as I like but at least it's coming in) I get the following errors in the log. I'm not sure what to do to fix them. 

![image](https://github.com/rg-engineering/ioBroker.sbfspot/assets/26743989/c66ae25d-bd3e-4009-a1ff-f218a9fe8df1)

![image](https://github.com/rg-engineering/ioBroker.sbfspot/assets/26743989/80f14979-b395-4e0d-8070-f72379fd0daf)

many thanks in advance!

**Comment by rg-engineering** [comment]
Please check the access rights of your folder, where you placed your sqlite database file. 

see also here:
https://forum.iobroker.net/topic/5555/neuer-adapter-sma-wechselrichter-mit-sbfspot/229

**Comment by runrennerrun** [comment]
okay, thanks for the quick reply. With which command I do this best? sudo chmod -R 775 . ?

**Comment by runrennerrun** [comment]
> okay, thanks for the quick reply. With which command I do this best? sudo chmod -R 775 . ?

sudo chown iobroker SBFspot.db
