### ISSUE TITLE
iobroker object tree structure for sbfspot.0 with empty value fields

### ISSUE THREAD

**Issue by sebastianlinz** [rg-engineering/ioBroker.sbfspot#38]
In iobroker's object tree no values are set for object sbfspot.0. All value fields are empty.

Setup is used with sqlite. After adapter startup object tree structure for sbfspot.0 is created. 

Log shows different select statements and result values on debug level (eg. serial number, type, total). Database access seems to work. Log ends with:

```
sbfspot.0 | 2020-07-26 16:45:01.512 | info | (32335) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
sbfspot.0 | 2020-07-26 16:45:01.511 | info | (32335) all done ...
sbfspot.0 | 2020-07-26 16:45:01.510 | debug | (32335) disconnect database
```

But object tree structure has empty value fields. 

Trying to access sbfspot object values from blockly's object chooser was not successfull. sbfspot adapter is not proposed.

**Comment by rg-engineering** [comment]
can you please show me a complete log (probably with deletion of serial number and data base query results if you want)

**Comment by sebastianlinz** [comment]
see part of log file:
[iobroker.2020-07-26.log](https://github.com/rg-engineering/ioBroker.sbfspot/files/4977912/iobroker.2020-07-26.log)

**Comment by sebastianlinz** [comment]
Could the issue be similiar to this: https://github.com/ioBroker/ioBroker.javascript/issues/405? There it says values should be "JSON.stringyfied".

**Comment by sebastianlinz** [comment]
I played around adding log statements. For example in main.js at line 962 total produced energy is available. But there seems to be an error writing state. Possibly it's not related to adapter's method "setState()". I tried it with simple pair "id" and "value" with no result. 

Maybe there's problem with the adapter object and my configuration. My iobroker is quite new, only a few days. Reading "https://github.com/ioBroker/ioBroker/wiki/Adapter-Development-Documentation#how-to-create-own-adapter" I found that creation of adapters seems to be changed. At least this could explain why sbspot adapter is not accessible from blocklys adapter chooser.

Hope this helps :-)

**Comment by rg-engineering** [comment]
can you please show me your object tree where you expect your data? should look like this:
![grafik](https://user-images.githubusercontent.com/8238668/88565502-ff666980-d034-11ea-8823-e88bf8b10f7f.png)

is your serial number shown as parent channel?
Do you run other adapters on the same system?

your log looks good, there is no problem...

**Comment by sebastianlinz** [comment]
this is how object tree looks like: 
![object_tree](https://user-images.githubusercontent.com/35873809/88569829-47888a80-d03b-11ea-88e2-e983037ab559.PNG)

yes, serial number is shown as parent channel id and name.

yes, I'm succefully running other adapters: eg. influxdb, smartmeter, sonoff, telegram

**Comment by sebastianlinz** [comment]
Object element "TotalPac" has a name. There is a difference in main.js line 207

**Comment by rg-engineering** [comment]
can you please delete sbfspot.0 and all children? and then run the adapter again?
after that can you please click on the edit pen of any state and post raw data (right hand side tab)
should look like this:
![grafik](https://user-images.githubusercontent.com/8238668/88571424-e7dfae80-d03d-11ea-8321-2b305429b199.png)


> There is a difference in main.js line 207

you mean the additional name in  adapter.extendObject? I added this to rename the name in existing installations (which works well here)
The problem here is that adapter.setObjectNotExists does not create a complete and valid datapoint...

**Comment by rg-engineering** [comment]
forget the previous post: I see the same probelm with a new clean installation.... need to fix it...

**Comment by rg-engineering** [comment]
@sebastianlinz please install latest version here from github. After installation version number should be 4.0.0 Please delete complete data tree from sbfspot.0 before...
