### ISSUE TITLE
HowTo: Battery Charge Stats for my ioBroker

### ISSUE THREAD

**Issue by anwelti** [rg-engineering/ioBroker.sbfspot#43]
Hello,

i use this setup:
ubuntu 20.04 LTS
iobroker
iobroker sbfspot-4.0-Adapter
sbfspot-3.7 for linux

I want to display my BatteryChargeStatus in ioBroker, but it doesnt get it from spfspot-DB.
How can i transfer this data to my ioBroker?

Thank you all very much.

**Comment by rg-engineering** [comment]
is this value available in sbfspot-DB?
