### ISSUE TITLE
wrong time format in mysql queries in DB_CalcHistory_Today

### ISSUE THREAD

**Issue by nisiode** [rg-engineering/ioBroker.sbfspot#8]
the used format 

> from_unixtime(TimeStamp, '%HH:%mm')

is not correct, becaue the lowercase **_m_** means the month.
correct should be an lowercase **_i_** for the minutes.

> from_unixtime(TimeStamp, '%HH:%im')

don't know why you used the letters twice ?!? maybe this is enough
> from_unixtime(TimeStamp, '%H:%i')

**Comment by rg-engineering** [comment]
I fixed that with latest commits.

**Comment by nisiode** [comment]
test ok, thanks
